//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Rmdy.Android.AdvancedRecyclerView")]
[assembly: AssemblyCompany("Rmdy")]
[assembly: AssemblyProduct("Rmdy.Android.AdvancedRecyclerView")]
[assembly: AssemblyVersion("0.11.1")]
[assembly: AssemblyFileVersion("0.11.1")]
[assembly: AssemblyInformationalVersion("0.11.1")]
[assembly: AssemblyCopyright("Copyright (c) 2020, Rmdy")]

